# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44831a5b7262cd466284ce1ee137a2950c90617e0e8cf08a0060d65790cfc90bef94f708befdb3cac412a455b9504ea4489286f69d21aec375674dc227d1929b

test:
  secret_key_base: 9bdb6a7cc1da5af1fa338c344cc4743127064cec918dc50c61e5b0468157ad5870dccdd353e7b429d148fea9c1e5988b00748d63f30e0ed4d46e1cf0d79a190d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
